const cfg=window.CHOICE_CONFIG||{apiBase:'',realtimeEnabled:false,lineOfficialUrl:''};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const makeId=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const clientId=localStorage.getItem('choice-client-id')||makeId();localStorage.setItem('choice-client-id',clientId);
const savedDisplayName=localStorage.getItem('choice-display-name')||'';
const stateKey='choice-app-v5';
const blank={title:'今晚吃什麼？',options:[],myVote:null,recent:[],roomCode:null,roomPassword:'',hostToken:'',displayName:savedDisplayName,lastDraw:null,phase:'setup',optionMode:'text',voteDeadline:'',anonymous:false,repeatVoting:false,votesPerPerson:1};
let data=load(),selectedVote=data.myVote||null,votesUsed=0,drawSelected=new Set(),roomSocket=null,roomMembers=[],throwing=false,pendingJoinCode='',pendingJoinLocked=false,micStream=null,audioCtx=null,analyser=null,meterRAF=null,isHost=false;
let voiceStream=null,voiceJoined=false,voiceMuted=false;
const voicePeers=new Map(),pendingIce=new Map();
const rtcConfig={iceServers:[{urls:'stun:stun.l.google.com:19302'}]};
const persistName=name=>{const n=String(name||'').trim().slice(0,20);data.displayName=n;localStorage.setItem('choice-display-name',n);return n};
function load(){try{return {...blank,...JSON.parse(localStorage.getItem(stateKey)||localStorage.getItem('choice-app-v4')||'{}')}}catch{return {...blank}}}
function save(){localStorage.setItem(stateKey,JSON.stringify(data))}
function api(path){return `${cfg.apiBase||''}${path}`}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(t){const e=$('#toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1800)}
function totalVotes(){return data.options.reduce((a,o)=>a+(o.votes||0),0)}
function topChoice(){const s=[...data.options].sort((a,b)=>(b.votes||0)-(a.votes||0));return s[0]&&s[0].votes?s[0]:null}
function phaseStep(){return data.phase==='voting'?'vote':data.phase==='closed'?'analysis':data.phase==='draw'?'draw':'setup'}
function voteLimit(){return data.repeatVoting?Math.min(20,Math.max(1,Number(data.votesPerPerson)||1)):1}
function voteExpired(){if(!data.voteDeadline)return false;const t=Date.parse(data.voteDeadline);return Number.isFinite(t)&&Date.now()>=t}
function localDeadlineValue(iso){if(!iso)return '';const d=new Date(iso);if(Number.isNaN(d.getTime()))return '';const z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}T${z(d.getHours())}:${z(d.getMinutes())}`}
function deadlineIso(value){if(!value)return '';const d=new Date(value);return Number.isNaN(d.getTime())?'':d.toISOString()}
function displayDate(value){const d=new Date(`${value}T00:00:00`);return Number.isNaN(d.getTime())?value:new Intl.DateTimeFormat('zh-TW',{year:'numeric',month:'numeric',day:'numeric',weekday:'short'}).format(d)}
async function readJsonResponse(r){const text=await r.text();if(!text)return {ok:false,error:`伺服器沒有回應（HTTP ${r.status}）`};try{return JSON.parse(text)}catch{return {ok:false,error:`伺服器回應格式錯誤（HTTP ${r.status}）`}}}

async function loadRoomList(){const list=$('#roomList');if(!list||data.roomCode)return;try{const r=await fetch(api('/api/rooms'),{cache:'no-store'}),j=await readJsonResponse(r);if(!r.ok)throw new Error(j.error||'讀取失敗');const rooms=Array.isArray(j.rooms)?j.rooms:[];list.innerHTML=rooms.map(room=>`<button class="room-list-item" type="button" data-room-code="${esc(room.code)}" data-locked="${room.locked?'1':'0'}"><span class="room-list-name">${esc(room.title||'未命名房間')}</span><span class="room-list-meta">${room.locked?'🔒':'進入'}</span></button>`).join('')}catch{list.innerHTML=''}}

function renderPlayers(){const list=$('#playerList'),status=$('#voteProgressText');if(!list||!status)return;let members=roomMembers;if(data.roomCode&&!members.length&&data.displayName)members=[{clientId,name:data.displayName,isHost,voted:votesUsed>0,voice:voiceJoined}];const voted=members.filter(m=>m.voted).length;if(data.phase==='voting'&&data.anonymous)status.textContent='匿名投票中';else status.textContent=data.phase==='voting'?`${voted}/${members.length} 已投票`:`${members.length} 人在線`;list.innerHTML=members.map(m=>`<div class="player-chip"><span class="player-name">${esc(m.name||'訪客')}${m.voice?' 🎙️':''}</span>${data.phase==='voting'&&!data.anonymous?`<span class="player-vote-state ${m.voted?'done':''}">${m.voted?'✓ 已投':'等待'}</span>`:`<span class="player-vote-state">${m.voice?'語音中':'在線'}</span>`}</div>`).join('')}

function updateVoiceUi(){const join=$('#joinVoiceBtn'),mute=$('#muteVoiceBtn'),leave=$('#leaveVoiceBtn'),status=$('#voiceStatus');if(!join||!mute||!leave||!status)return;const onlineVoice=roomMembers.filter(m=>m.voice).length;join.disabled=!data.roomCode||roomSocket?.readyState!==1||voiceJoined;join.classList.toggle('hidden',voiceJoined);mute.classList.toggle('hidden',!voiceJoined);leave.classList.toggle('hidden',!voiceJoined);mute.textContent=voiceMuted?'解除靜音':'靜音';status.textContent=!data.roomCode?'先進入房間':voiceJoined?`${Math.max(1,onlineVoice)} 人在語音`:'可加入房間語音'}

function renderSetupControls(){const text=$('#optionTextMode'),date=$('#optionDateMode'),input=$('#optionInput'),deadline=$('#voteDeadlineInput'),anon=$('#anonymousVoteInput'),repeat=$('#repeatVoteInput'),count=$('#votesPerPersonInput');text?.classList.toggle('active',data.optionMode!=='date');date?.classList.toggle('active',data.optionMode==='date');if(input){input.type=data.optionMode==='date'?'date':'text';input.disabled=!isHost||data.phase!=='setup'}if(deadline&&document.activeElement!==deadline)deadline.value=localDeadlineValue(data.voteDeadline);if(anon)anon.checked=!!data.anonymous;if(repeat)repeat.checked=!!data.repeatVoting;if(count){count.value=String(voteLimit());count.disabled=!isHost||data.phase!=='setup'||!data.repeatVoting}}

function render(){
  $('#homeView')?.classList.toggle('hidden',!!data.roomCode);$('#roomView')?.classList.toggle('hidden',!data.roomCode);
  if($('#roomTitle'))$('#roomTitle').textContent=data.title||'我的 Choice';if($('#roomCodeText'))$('#roomCodeText').textContent=data.roomCode||'——';if($('#participantCount'))$('#participantCount').textContent=`${Math.max(1,roomMembers.length)} 人`;if($('#roleBadge')){$('#roleBadge').classList.toggle('host',isHost)}
  renderPlayers();updateVoiceUi();renderSetupControls();
  if($('#pollTitleDisplay'))$('#pollTitleDisplay').textContent=data.title||'投票';
  if($('#addOptionBtn'))$('#addOptionBtn').disabled=!isHost||data.phase!=='setup';
  if($('#setupOptions'))$('#setupOptions').innerHTML=data.options.map(o=>`<span class="setup-chip">${esc(o.name)}${isHost&&data.phase==='setup'?`<button data-remove="${o.id}">×</button>`:''}</span>`).join('');
  $('#goVoteBtn')?.classList.toggle('hidden',!isHost||data.phase!=='setup');$('#goDrawBtn')?.classList.toggle('hidden',!isHost||data.phase!=='setup');$('#deleteRoomBtn')?.classList.toggle('hidden',!isHost);
  const expired=voteExpired(),limit=voteLimit(),remaining=Math.max(0,limit-votesUsed),canVote=data.phase==='voting'&&!expired&&remaining>0;
  if($('#voteOptions'))$('#voteOptions').innerHTML=data.options.map(o=>`<button class="vote-option ${selectedVote===o.id?'selected':''}" data-vote="${o.id}" ${canVote?'':'disabled'}>${esc(o.name)} · ${o.votes||0}票</button>`).join('');
  if($('#voteBtn')){$('#voteBtn').disabled=!selectedVote||data.options.length<2||!canVote;$('#voteBtn').textContent=data.repeatVoting?`蓋章投票（剩 ${remaining} 票）`:'蓋章投票'}
  if($('#voteDeadlineText'))$('#voteDeadlineText').textContent=data.voteDeadline?`${expired?'已截止':'截止'}：${new Date(data.voteDeadline).toLocaleString('zh-TW')}`:'';
  $('#closeVoteBtn')?.classList.toggle('hidden',!isHost||data.phase!=='voting');
  const total=totalVotes();if($('#chartList'))$('#chartList').innerHTML=data.options.map(o=>{const p=total?Math.round((o.votes||0)/total*100):0;return `<div class="bar-row"><div class="bar-label">${esc(o.name)}</div><div class="bar-track"><div class="bar-fill" style="width:${p}%"></div></div><div class="bar-value">${p}%</div></div>`}).join('')||'<p class="small-note">尚未投票</p>';
  const top=topChoice();if($('#insightText'))$('#insightText').textContent=top?`目前第一名：${top.name}（${top.votes} 票）`:'尚未投票';
  $('#analysisDrawBtn')?.classList.toggle('hidden',!isHost);$('#announceVoteBtn')?.classList.toggle('hidden',!isHost);
  if(!drawSelected.size)data.options.forEach(o=>drawSelected.add(o.id));for(const id of [...drawSelected])if(!data.options.some(o=>o.id===id))drawSelected.delete(id);
  if($('#drawChecks'))$('#drawChecks').innerHTML=data.options.map(o=>`<label class="draw-check"><input type="checkbox" data-draw="${o.id}" ${drawSelected.has(o.id)?'checked':''} ${!isHost?'disabled':''}>${esc(o.name)}</label>`).join('');
  $('#throwBtn')?.classList.toggle('hidden',!isHost);if($('#drawResult'))$('#drawResult').textContent=data.lastDraw?`🎯 ${data.lastDraw}`:'準備好了嗎？';$('#announceDrawBtn')?.classList.toggle('hidden',!isHost||!data.lastDraw);
  $$('#flowNav button').forEach(b=>{const step=b.dataset.step;if(!isHost)b.disabled=true;else b.disabled=data.phase!=='setup'&&step==='setup'});
}
function showStep(name,force=false){if(!force&&!isHost&&name!==phaseStep())return;$$('.step').forEach(e=>e.classList.toggle('active',e.id===`${name}Step`));$$('#flowNav button').forEach(b=>b.classList.toggle('active',b.dataset.step===name));window.scrollTo({top:0,behavior:'smooth'})}
function roomState(){return {title:data.title,options:data.options,recent:data.recent,lastDraw:data.lastDraw,phase:data.phase,optionMode:data.optionMode,voteDeadline:data.voteDeadline,anonymous:data.anonymous,repeatVoting:data.repeatVoting,votesPerPerson:voteLimit()}}
function send(payload){try{if(roomSocket?.readyState===1)roomSocket.send(JSON.stringify(payload))}catch{}}
function sync(){if(isHost&&data.phase==='setup')send({type:'state:set',state:roomState()})}
function applyState(s,myVote=null,hostFlag=null,newVotesUsed=0){if(!s)return;data.title=s.title||data.title;data.options=Array.isArray(s.options)?s.options:data.options;data.recent=Array.isArray(s.recent)?s.recent:data.recent;data.lastDraw=s.lastDraw||null;data.phase=s.phase||'setup';data.optionMode=s.optionMode==='date'?'date':'text';data.voteDeadline=s.voteDeadline||'';data.anonymous=!!s.anonymous;data.repeatVoting=!!s.repeatVoting;data.votesPerPerson=Math.min(20,Math.max(1,Number(s.votesPerPerson)||1));if(hostFlag!==null)isHost=!!hostFlag;data.myVote=myVote||null;votesUsed=Math.max(0,Number(newVotesUsed)||0);selectedVote=data.myVote;if(selectedVote&&!data.options.some(o=>o.id===selectedVote))selectedVote=null;save();render();showStep(phaseStep(),true)}
function clearRoomState(){stopVoice(false);roomMembers=[];data.roomCode=null;data.roomPassword='';data.hostToken='';data.myVote=null;isHost=false;selectedVote=null;votesUsed=0;pendingJoinCode='';pendingJoinLocked=false;save();history.replaceState({},'',location.pathname);render();showStep('setup',true);setTimeout(loadRoomList,120)}
function openJoinDialog(code,locked=true){pendingJoinCode=String(code||'').toUpperCase();pendingJoinLocked=!!locked;if($('#joinNameInput'))$('#joinNameInput').value=data.displayName||localStorage.getItem('choice-display-name')||'';if($('#joinPasswordInput'))$('#joinPasswordInput').value='';$('#joinPasswordLabel')?.classList.toggle('hidden',!pendingJoinLocked);$('#joinDialog')?.showModal();setTimeout(()=>$('#joinPasswordInput')?.focus(),40)}

async function createRoom(){const name=persistName($('#hostNameInput')?.value),title=$('#roomTopicInput')?.value.trim()||'我的 Choice',password=$('#roomPasswordInput')?.value.trim()||'';if(!name)return toast('請輸入名稱');data={...blank,title,roomPassword:password,displayName:name};selectedVote=null;votesUsed=0;drawSelected.clear();try{const r=await fetch(api('/api/rooms'),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({password,state:roomState()})}),j=await readJsonResponse(r);if(!r.ok||!j.code)throw new Error(j.error||`建立失敗（HTTP ${r.status}）`);data.roomCode=j.code;data.hostToken=j.hostToken||'';isHost=true;save();$('#openRoomDialog')?.close();connectRoom();render();showStep('setup',true);toast(`房間 ${j.code} 已建立`)}catch(e){toast(e.message||'無法建立房間');throw e}}
function connectRoom(){if(!data.roomCode)return;if(roomSocket)try{roomSocket.onclose=null;roomSocket.close()}catch{}const u=new URL(api(`/api/rooms/${data.roomCode}/ws`),location.href);u.searchParams.set('clientId',clientId);u.searchParams.set('name',data.displayName||'訪客');if(data.roomPassword)u.searchParams.set('password',data.roomPassword);if(data.hostToken)u.searchParams.set('hostToken',data.hostToken);u.protocol=u.protocol==='https:'?'wss:':'ws:';try{roomSocket=new WebSocket(u);roomSocket.onopen=()=>{send({type:'join'});render()};roomSocket.onmessage=async e=>{let m;try{m=JSON.parse(e.data)}catch{return}if(m.type==='snapshot')applyState(m.state,m.myVote,m.isHost,m.votesUsed);if(m.type==='members'){roomMembers=m.members||[];const activeVoice=new Set(roomMembers.filter(x=>x.voice).map(x=>x.clientId));for(const id of [...voicePeers.keys()])if(!activeVoice.has(id))closeVoicePeer(id);render()}if(m.type==='voice:peers'&&voiceJoined){for(const peer of m.peers||[])await ensureVoicePeer(peer.clientId,true)}if(m.type==='voice:signal'&&voiceJoined)await handleVoiceSignal(m.from,m.data);if(m.type==='voice:left')closeVoicePeer(m.clientId);if(m.type==='announce')showAnnouncement(m.result);if(m.type==='draw:start'){if(Array.isArray(m.optionIds)){drawSelected=new Set(m.optionIds);render()}showStep('draw',true);const dart=$('#dart');if(dart){dart.classList.remove('fly');void dart.offsetWidth;dart.classList.add('fly')}if($('#drawResult'))$('#drawResult').textContent='射鏢飛行中…'}if(m.type==='draw'&&m.name){data.lastDraw=m.name;save();render();showStep('draw',true);toast(`🎯 抽中 ${m.name}`)}if(m.type==='vote:ack'){votesUsed=Math.max(votesUsed,Number(m.votesUsed)||1);data.myVote=m.optionId||data.myVote;save();const f=$('#stampFx');if(f){f.classList.remove('show');void f.offsetWidth;f.classList.add('show')}render();toast(data.repeatVoting?`已投票，剩 ${Math.max(0,voteLimit()-votesUsed)} 票`:'已投票 ✓')}if(m.type==='room:closed'){toast('房間已刪除');clearRoomState()}if(m.type==='error')toast(m.message||'操作失敗')};roomSocket.onclose=e=>{roomMembers=[];stopVoice(false);render();if(e.code===4001){const room=data.roomCode;data.roomCode=null;data.roomPassword='';data.hostToken='';isHost=false;save();render();openJoinDialog(room,true);toast('請輸入房間密碼');return}if(e.code===4004||e.code===4005){clearRoomState();if(e.code===4004)toast('房間不存在或已失效')}}}catch{toast('連線失敗')}}
function attemptJoin(code,password='',name=''){code=String(code||'').trim().toUpperCase();if(!/^[A-Z0-9]{6}$/.test(code))return toast('房間不存在');const displayName=persistName(name||data.displayName);if(!displayName)return toast('請輸入名稱');data.roomCode=code;data.roomPassword=password;data.hostToken='';data.displayName=displayName;isHost=false;pendingJoinCode=code;save();render();connectRoom()}
async function shareRoom(){const u=new URL(location.href);u.searchParams.set('room',data.roomCode);try{if(navigator.share)await navigator.share({title:data.title,text:`加入 Choice：${data.roomCode}`,url:u.href});else{await navigator.clipboard.writeText(u.href);toast('邀請連結已複製')}}catch{}}
function deleteRoom(){if(!isHost)return;if(!confirm('確定要永久刪除這個房間嗎？刪除後所有人都無法再進入。'))return;send({type:'room:close'})}

async function ensureVoicePeer(peerId,offerer=false){if(!peerId||peerId===clientId||!voiceStream)return null;if(voicePeers.has(peerId))return voicePeers.get(peerId);const pc=new RTCPeerConnection(rtcConfig);voicePeers.set(peerId,pc);voiceStream.getTracks().forEach(track=>pc.addTrack(track,voiceStream));pc.onicecandidate=e=>{if(e.candidate)send({type:'voice:signal',to:peerId,data:{candidate:e.candidate}})};pc.ontrack=e=>{let audio=document.getElementById(`voice-audio-${peerId}`);if(!audio){audio=document.createElement('audio');audio.id=`voice-audio-${peerId}`;audio.autoplay=true;audio.playsInline=true;$('#voiceAudioRack')?.appendChild(audio)}audio.srcObject=e.streams[0];audio.play().catch(()=>{})};pc.onconnectionstatechange=()=>{if(['failed','closed'].includes(pc.connectionState))closeVoicePeer(peerId)};if(offerer){const offer=await pc.createOffer();await pc.setLocalDescription(offer);send({type:'voice:signal',to:peerId,data:{description:pc.localDescription}})}return pc}
async function flushIce(peerId,pc){const list=pendingIce.get(peerId)||[];pendingIce.delete(peerId);for(const c of list)try{await pc.addIceCandidate(c)}catch{}}
async function handleVoiceSignal(from,payload){if(!from||!payload)return;const pc=await ensureVoicePeer(from,false);if(!pc)return;try{if(payload.description){await pc.setRemoteDescription(payload.description);await flushIce(from,pc);if(payload.description.type==='offer'){const answer=await pc.createAnswer();await pc.setLocalDescription(answer);send({type:'voice:signal',to:from,data:{description:pc.localDescription}})}}if(payload.candidate){if(pc.remoteDescription)await pc.addIceCandidate(payload.candidate);else{const list=pendingIce.get(from)||[];list.push(payload.candidate);pendingIce.set(from,list)}}}catch(err){console.warn('voice signal error',err)}}
function closeVoicePeer(peerId){const pc=voicePeers.get(peerId);if(pc)try{pc.close()}catch{}voicePeers.delete(peerId);pendingIce.delete(peerId);document.getElementById(`voice-audio-${peerId}`)?.remove()}
function startMeter(stream){stopMeter();try{audioCtx=new (window.AudioContext||window.webkitAudioContext)();const src=audioCtx.createMediaStreamSource(stream);analyser=audioCtx.createAnalyser();src.connect(analyser);const tick=()=>{if(!analyser)return;const a=new Uint8Array(analyser.frequencyBinCount);analyser.getByteFrequencyData(a);const avg=a.reduce((x,y)=>x+y,0)/Math.max(1,a.length);if($('#voiceMeterBar'))$('#voiceMeterBar').style.width=`${Math.min(100,avg*1.6)}%`;meterRAF=requestAnimationFrame(tick)};tick()}catch{}}
function stopMeter(){if(meterRAF)cancelAnimationFrame(meterRAF);meterRAF=null;analyser=null;if(audioCtx)audioCtx.close().catch(()=>{});audioCtx=null;if($('#voiceMeterBar'))$('#voiceMeterBar').style.width='0'}
async function joinVoice(){if(!data.roomCode||roomSocket?.readyState!==1)return toast('請先進入房間');if(voiceJoined)return;try{if(micStream)stopMicTest();voiceStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});voiceJoined=true;voiceMuted=false;startMeter(voiceStream);send({type:'voice:join'});render();toast('已加入語音')}catch{toast('無法取得麥克風權限')}}
function toggleVoiceMute(){if(!voiceJoined||!voiceStream)return;voiceMuted=!voiceMuted;voiceStream.getAudioTracks().forEach(t=>t.enabled=!voiceMuted);render();toast(voiceMuted?'已靜音':'已解除靜音')}
function stopVoice(notify=true){if(!voiceJoined&&!voiceStream)return;if(notify)send({type:'voice:leave'});for(const id of [...voicePeers.keys()])closeVoicePeer(id);voiceStream?.getTracks().forEach(t=>t.stop());voiceStream=null;voiceJoined=false;voiceMuted=false;stopMeter();render()}
async function toggleMicTest(){if(voiceJoined)return toast('已在房間語音中');try{if(micStream){stopMicTest();return}micStream=await navigator.mediaDevices.getUserMedia({audio:true});startMeter(micStream);if($('#micTestBtn'))$('#micTestBtn').textContent='停止測試'}catch{toast('無法取得麥克風權限')}}
function stopMicTest(){micStream?.getTracks().forEach(t=>t.stop());micStream=null;stopMeter();if($('#micTestBtn'))$('#micTestBtn').textContent='測試麥克風'}

$('#openRoomBtn')&&( $('#openRoomBtn').onclick=()=>{$('#hostNameInput').value=data.displayName||localStorage.getItem('choice-display-name')||'';$('#openRoomDialog').showModal()} );
$('#roomList')&&( $('#roomList').onclick=e=>{const b=e.target.closest('[data-room-code]');if(b)openJoinDialog(b.dataset.roomCode,b.dataset.locked==='1')} );
$('#createRoomBtn')&&( $('#createRoomBtn').onclick=createRoom );
$('#joinWithPasswordBtn')&&( $('#joinWithPasswordBtn').onclick=()=>{const name=$('#joinNameInput')?.value.trim()||data.displayName,p=pendingJoinLocked?$('#joinPasswordInput')?.value||'':'';if(!name)return toast('請先在首頁輸入名稱');$('#joinDialog')?.close();attemptJoin(pendingJoinCode,p,name)} );
$('#shareRoomBtn')&&( $('#shareRoomBtn').onclick=shareRoom );$('#deleteRoomBtn')&&( $('#deleteRoomBtn').onclick=deleteRoom );
$$('#flowNav button').forEach(b=>b.onclick=()=>{if(isHost)showStep(b.dataset.step)});
function setOptionMode(mode){if(!isHost||data.phase!=='setup')return;data.optionMode=mode==='date'?'date':'text';if($('#optionInput'))$('#optionInput').value='';save();render();sync()}
$('#optionTextMode')&&( $('#optionTextMode').onclick=()=>setOptionMode('text') );$('#optionDateMode')&&( $('#optionDateMode').onclick=()=>setOptionMode('date') );
function addOption(){if(!isHost||data.phase!=='setup')return;const input=$('#optionInput');let raw=input?.value.trim()||'';if(!raw)return;const name=data.optionMode==='date'?displayDate(raw):raw;if(data.options.length>=30)return toast('最多 30 個項目');if(data.options.some(o=>o.name===name))return toast('項目重複');const id=makeId();data.options.push({id,name,votes:0});drawSelected.add(id);input.value='';save();render();sync()}
$('#addOptionBtn')&&( $('#addOptionBtn').onclick=addOption );$('#optionInput')&&( $('#optionInput').onkeydown=e=>{if(e.key==='Enter')addOption()} );
$('#setupOptions')&&( $('#setupOptions').onclick=e=>{if(!isHost||data.phase!=='setup')return;const b=e.target.closest('[data-remove]');if(!b)return;data.options=data.options.filter(o=>o.id!==b.dataset.remove);drawSelected.delete(b.dataset.remove);save();render();sync()} );
function syncSettings(){if(!isHost||data.phase!=='setup')return;data.voteDeadline=deadlineIso($('#voteDeadlineInput')?.value||'');data.anonymous=!!$('#anonymousVoteInput')?.checked;data.repeatVoting=!!$('#repeatVoteInput')?.checked;data.votesPerPerson=data.repeatVoting?Math.min(20,Math.max(1,Number($('#votesPerPersonInput')?.value)||1)):1;save();render();sync()}
$('#voteDeadlineInput')&&( $('#voteDeadlineInput').onchange=syncSettings );$('#anonymousVoteInput')&&( $('#anonymousVoteInput').onchange=syncSettings );$('#repeatVoteInput')&&( $('#repeatVoteInput').onchange=syncSettings );$('#votesPerPersonInput')&&( $('#votesPerPersonInput').onchange=syncSettings );
$('#goVoteBtn')&&( $('#goVoteBtn').onclick=()=>{if(data.options.length<2)return toast('至少要有 2 個項目');syncSettings();sync();send({type:'phase',phase:'voting'})} );$('#goDrawBtn')&&( $('#goDrawBtn').onclick=()=>{if(data.options.length<2)return toast('至少要有 2 個項目');sync();send({type:'phase',phase:'draw'})} );
$('#voteOptions')&&( $('#voteOptions').onclick=e=>{const b=e.target.closest('[data-vote]');if(!b||data.phase!=='voting'||voteExpired()||votesUsed>=voteLimit())return;selectedVote=b.dataset.vote;render()} );$('#voteBtn')&&( $('#voteBtn').onclick=()=>{if(!selectedVote||data.phase!=='voting')return;send({type:'vote',optionId:selectedVote})} );$('#closeVoteBtn')&&( $('#closeVoteBtn').onclick=()=>send({type:'phase',phase:'closed'}) );$('#analysisDrawBtn')&&( $('#analysisDrawBtn').onclick=()=>send({type:'phase',phase:'draw'}) );$('#announceVoteBtn')&&( $('#announceVoteBtn').onclick=()=>{const t=topChoice();if(!t)return toast('目前沒有投票結果');announce(t.name)} );
$('#drawChecks')&&( $('#drawChecks').onchange=e=>{if(!isHost)return;const c=e.target.closest('[data-draw]');if(!c)return;c.checked?drawSelected.add(c.dataset.draw):drawSelected.delete(c.dataset.draw)} );$('#throwBtn')&&( $('#throwBtn').onclick=()=>{if(!isHost||throwing)return;const ids=[...drawSelected].filter(id=>data.options.some(o=>o.id===id));if(ids.length<2)return toast('至少勾選 2 個項目');throwing=true;data.lastDraw=null;save();render();send({type:'draw:request',optionIds:ids});setTimeout(()=>{throwing=false},1100)} );$('#announceDrawBtn')&&( $('#announceDrawBtn').onclick=()=>{if(data.lastDraw)announce(data.lastDraw)} );
function announce(result){if(!isHost)return;send({type:'announce',result});showAnnouncement(result)}function showAnnouncement(result){if($('#announceResult'))$('#announceResult').textContent=result;$('#announceDialog')?.showModal()}
$('#voiceBtn')&&( $('#voiceBtn').onclick=()=>{updateVoiceUi();$('#voiceDialog').showModal()} );$('#micTestBtn')&&( $('#micTestBtn').onclick=toggleMicTest );$('#joinVoiceBtn')&&( $('#joinVoiceBtn').onclick=joinVoice );$('#muteVoiceBtn')&&( $('#muteVoiceBtn').onclick=toggleVoiceMute );$('#leaveVoiceBtn')&&( $('#leaveVoiceBtn').onclick=()=>stopVoice(true) );$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog')?.close());
const roomFromUrl=new URL(location.href).searchParams.get('room');if(roomFromUrl&&/^[A-Za-z0-9]{6}$/.test(roomFromUrl)){openJoinDialog(roomFromUrl.toUpperCase(),true)}else if(data.roomCode&&data.displayName)connectRoom();render();loadRoomList();setInterval(()=>{if(!data.roomCode)loadRoomList();else if(data.phase==='voting')render()},5000);
